version: "3.9"

services:
  backend:
    container_name: project_fullstack_kenzie_backend
    build: 
      dockerfile: Dockerfile
      context: "./backend"
    ports:
      - 3000:3000
    depends_on:
      - postgres
    command: bash -c "yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - /app/node_modules
      - ./backend:/app

  postgres:
    container_name: db_project_fullstack_kenzie
    image: postgres:latest
    ports:
      - 5434:5432
    env_file:
      - ./backend/.env
